INSERT  IGNORE INTO stock (symbol, name, exchange, current_price) VALUES
('AAPL','Apple Inc.','NASDAQ',0),
('TSLA','Tesla Inc.','NASDAQ',0),
('GOOGL','Alphabet Inc.','NASDAQ',0),
('AMZN','Amazon.com Inc.','NASDAQ',0),
('MSFT','Microsoft Corp.','NASDAQ',0),
('NFLX','Netflix Inc.','NASDAQ',0),
('META','Meta Platforms','NASDAQ',0),
('NVDA','NVIDIA Corp.','NASDAQ',0),
('BABA','Alibaba Group','NYSE',0),
('INTC','Intel Corp.','NASDAQ',0),
('AMD','Advanced Micro Devices','NASDAQ',0),
('ORCL','Oracle Corp.','NYSE',0),
('IBM','IBM Corp.','NYSE',0),
('ADBE','Adobe Inc.','NASDAQ',0),
('PYPL','PayPal Holdings','NASDAQ',0),
('CRM','Salesforce Inc.','NYSE',0),
('UBER','Uber Technologies','NYSE',0),
('LYFT','Lyft Inc.','NASDAQ',0),
('SHOP','Shopify Inc.','NYSE',0),
('SQ','Block Inc.','NYSE',0),
('TWTR','Twitter Inc.','NYSE',0),
('SNAP','Snap Inc.','NYSE',0),
('SPOT','Spotify Technology','NYSE',0),
('DIS','Disney','NYSE',0),
('BA','Boeing','NYSE',0),
('GM','General Motors','NYSE',0),
('F','Ford Motor Co.','NYSE',0),
('V','Visa Inc.','NYSE',0),
('MA','Mastercard Inc.','NYSE',0),
('KO','Coca-Cola Co.','NYSE',0);